### ISSUE TITLE
Possible Bug, getting ahealed and then going to the experimental pod deletes your character

### ISSUE THREAD

**Issue by AGasCanister** [PersistentSS13/Nebula#201]
This happened to me recently and in this case I got ahealed various times thanks to the perma sleep bug, when I got into the experimental pod, the lonely pod to the east of the room I got sent back to the lobby and when I tried to re join the game, I got sent to the background room, where I need to select my 2 primary "jobs". After this I went back to the experimental pod and I could rejoin as my new character (didn't got ahealed).

I also must add that I couldn't read Cortical Chat

**Comment by genessee-forgot-his-password-again** [comment]
This probably has something to do with your lack of a Cortical Chat when you entered the cryopod. A-healing removes your cortical stack, and if I were to guess I'd bet the game checks for your cortical stack when logging back in. Since you didn't have one, it assumed you didn't have a character and went on as though you were a new player.

See if going into the experimental pod without a cortical stack causes the same bug, maybe?

**Comment by PsyCommando** [comment]
Was a bug with players getting de-linked with their saved limbo data. Which made the cryopod code crash. Was fixed.
